# Generated by Django 4.1 on 2024-03-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='max_cars_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='max_cars_count',
            field=models.IntegerField(default=1),
        ),
    ]
