# Generated by Django 4.1 on 2025-02-20 08:42

from django.db import migrations, models
import django.db.models.deletion
import location.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraInLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('mode', models.CharField(blank=True, choices=[(None, 'Проста камера'), ('in', 'Вход'), ('out', 'Выход')], max_length=255, null=True, verbose_name='Собития')),
            ],
            options={
                'verbose_name': 'Камера в локации',
                'verbose_name_plural': 'Камеры в локации',
            },
        ),
        migrations.CreateModel(
            name='CarInLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False, verbose_name='Блокирован')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCameraInLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('mode', models.CharField(blank=True, choices=[(None, 'Проста камера'), ('in', 'Вход'), ('out', 'Выход')], max_length=255, null=True, verbose_name='Собития')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Камера в локации',
                'verbose_name_plural': 'historical Камеры в локации',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCarInLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False, verbose_name='Блокирован')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical car in location',
                'verbose_name_plural': 'historical car in locations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('max_count_cars', models.IntegerField(verbose_name='Кол-во машин')),
                ('max_count_users', models.IntegerField(verbose_name='Кол-во пользователи')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Локация',
                'verbose_name_plural': 'historical Локации',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserInLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('max_count_cars', models.IntegerField(default=1, verbose_name='Кол-во машин')),
                ('status', models.CharField(choices=[('checking', 'На проверке'), ('accepted', 'Принята')], default='checking', max_length=255, verbose_name='Статус')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ')], default='user', max_length=255, verbose_name='Роль')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Пользователи и заявки',
                'verbose_name_plural': 'historical Пользователи и заявки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('car_number', models.CharField(max_length=255, verbose_name='Номер машини')),
                ('mode', models.CharField(choices=[(None, 'Проста камера'), ('in', 'Вход'), ('out', 'Выход')], default='in', max_length=255, verbose_name='Собития')),
            ],
            options={
                'verbose_name': 'История локации',
                'verbose_name_plural': 'Истории локации',
            },
        ),
        migrations.CreateModel(
            name='InviteUUID',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(default=location.models.invite_expires_at, verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'Инвайт',
                'verbose_name_plural': 'Инвайти',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('max_count_cars', models.IntegerField(verbose_name='Кол-во машин')),
                ('max_count_users', models.IntegerField(verbose_name='Кол-во пользователи')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='UserInLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_count_cars', models.IntegerField(default=1, verbose_name='Кол-во машин')),
                ('status', models.CharField(choices=[('checking', 'На проверке'), ('accepted', 'Принята')], default='checking', max_length=255, verbose_name='Статус')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ')], default='user', max_length=255, verbose_name='Роль')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Пользователи и заявки',
                'verbose_name_plural': 'Пользователи и заявки',
            },
        ),
    ]
