# Generated by Django 4.1 on 2025-02-20 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0002_initial'),
        ('camera', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='inviteuuid',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='history',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='history',
            name='car_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='history',
            name='cil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.camerainlocation', verbose_name='Камера в локации'),
        ),
        migrations.AddField(
            model_name='historicaluserinlocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluserinlocation',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='historicaluserinlocation',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcarinlocation',
            name='car',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='car.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='historicalcarinlocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcarinlocation',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='historicalcamerainlocation',
            name='camera',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='camera.camera', verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='historicalcamerainlocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcamerainlocation',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='carinlocation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='carinlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='camerainlocation',
            name='camera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camera.camera', verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='camerainlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Локация'),
        ),
        migrations.AlterUniqueTogether(
            name='userinlocation',
            unique_together={('user', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='carinlocation',
            unique_together={('car', 'location')},
        ),
    ]
