# Generated by Django 4.1 on 2024-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_historicallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinlocation',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcarinlocation',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluserinlocation',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinlocation',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=255),
        ),
    ]
