# Generated by Django 4.1 on 2024-03-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_camerainlocation_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerainlocation',
            name='mode',
            field=models.CharField(blank=True, choices=[(None, 'Проста камера'), ('in', 'Вход'), ('out', 'Выход')], max_length=255, null=True),
        ),
    ]
