# Generated by Django 4.1 on 2024-03-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_camerainlocation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='mode',
            field=models.CharField(choices=[(None, 'Проста камера'), ('in', 'Вход'), ('out', 'Выход')], default='in', max_length=255),
        ),
    ]
