# Generated by Django 4.1 on 2024-03-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машини'},
        ),
        migrations.AlterModelOptions(
            name='historicalcar',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Машина', 'verbose_name_plural': 'historical Машини'},
        ),
    ]
