# Generated by Django 4.1 on 2024-03-27 11:45

import car.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_number_alter_historicalcar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=255, validators=[car.validators.car_number_validator]),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='number',
            field=models.CharField(max_length=255, validators=[car.validators.car_number_validator]),
        ),
    ]
