name: Docker Compose CI

on: push

jobs:

  build:
    runs-on: self.hosted
    steps:
    - uses: actions/checkout@v4
    - name: Down the Docker containers
      run: docker-compose -f docker-compose.prod.yml down
      
    - name: Build the Docker image
      run: docker-compose -f docker-compose.prod.yml build

    - name: Run Docker compose
      run: docker-compose -f docker-compose.prod.yml up -d    
